### ISSUE TITLE
Scrapy-Cluster doesn't respect the Request type

### ISSUE THREAD

**Issue by wenxzhen** [istresearch/scrapy-cluster#108]
From the code below, we can see that scrapy-cluster only reads the url of the request from Redis Queue. But in some cases, we may define the request type by subclass the default Request. One example is the SplashRequest. 

Can we support such kind of case?

```
item = self.find_item()
        if item:
            self.logger.debug("Found url to crawl {url}" \
                    .format(url=item['url']))
            try:
                req = Request(item['url'])
            except ValueError:
                # need absolute url
                # need better url validation here
                req = Request('http://' + item['url'])
```

**Comment by joequery** [comment]
Relates to #94 (Specifically [this comment](https://github.com/istresearch/scrapy-cluster/issues/94#issuecomment-277587175))

**Comment by madisonb** [comment]
If this is a serialization problem of the Request itself, we would need to modify both https://git.io/vStno and https://git.io/vStRT to support multiple different kinds of requests in the scheduler. We could then use something like [this](http://stackoverflow.com/questions/2020014/get-fully-qualified-class-name-of-an-object-in-python) to be able to dynamically import new Requests, assuming here that they don't deviate from the baseline `Request` class too much.

**Comment by wenxzhen** [comment]
@madisonb any plan to fix this?

**Comment by madisonb** [comment]
If you are referencing [this](https://git.io/vSYLz), it appears like we would need to add the following keys:
* splash

However, we already pass through all known `meta` keys, and if the `splash` key is within that, I don't think we have to do anything different at all, because all of these keys appears to be under the `splash` key, like `meta.splash.XXX`.
* endpoint
* slot_policy
* splash_url
* splash_headers
* dont_process_response
* magic_response
* dont_send_headers
* http_status_from_error_code
* cache_args
* args

but you can verify that by printing out what the `meta` field of the request is. We can go two routes for solving this:
a) Hardcode if we detect the `splash` meta field that it is a SplashRequest, vs a normal Request. This would only support those two types of requests
b) using dynamic imports, serialize the class module path and do the import on the fly from the request. Kind of like adding 
```
{
module: 'my.class.path'
class: 'TypeOfRequest'
}
```
to the serialized Request, and in the scheduler doing a dynamic import of the class if it doesn't exist.

The latter is more complex but more complete, while the former enables Scrapy Cluster to work with Scrapy Splash, which has been a long asked for feature.

I am going to leave this ticket open, as I think it is worth doing, however it is going to be in v1.3. If anyone sees this and wants to tackle it, please submit a PR to the `dev` branch.

**Comment by madisonb** [comment]
Closing as the PR above fixes this issue
