### ISSUE TITLE
Zookeeper watcher's behavior is different on python  3

### ISSUE THREAD

**Issue by gas1121** [istresearch/scrapy-cluster#128]
On python 2.7, when I run`python example_zw.py -z zookeeper:2181 -f "/" --event`, I got:
```
('The valid state is now', True)
Use a keyboard interrupt to shut down the process.
```
On python 3.6, when I run`python example_zw.py -z zookeeper:2181 -f "/" --event`, I got:
```
Your file contents: b''
The valid state is now True
Use a keyboard interrupt to shut down the process.
```
The **config_handler** will be called once when zookeeper watcher starts, so in crawler there will be
`Zookeeper config wiped` and `Lost config from Zookeeper` in log

**Comment by madisonb** [comment]
Does this recover once the crawler boots up? So the workflow is:
- init crawler process
- lost config from zk
- zk config wiped
- zk config changed

**Comment by gas1121** [comment]
the workflow is:
+ init crawler process
+ zk config changed callback called with empty string
+ `Zookeeper config wiped` was logged
+ `Lost config from Zookeeper` was logged

after that crawler seems to work as normal

**Comment by madisonb** [comment]
Hmm, I would need to compare it to the crawler output from 2.7, if that is indeed the log messages the ZookeeperWatcher class may not be python 3 compatible, can we reproduce the error within [example_zw.py](https://scrapy-cluster.readthedocs.io/en/latest/topics/utils/zookeeperwatcher.html#example)? If so, this means the zookeeper watcher class wont behave properly and it needs to be addressed. Otherwise if that example script works as expected, the crawler should too.

**Comment by gas1121** [comment]
Yes, this error can be reproduced within example_zw.py.

**Comment by madisonb** [comment]
Ok, so that is going to be a blocker on #126 until we get that resolved, if the examples don't function the way they are supposed to we will lose functionality, and it is going to cripple the python3 version of the project.

**Comment by madisonb** [comment]
This has been corrected, closing.
