### ISSUE TITLE
Redis server failed，what should I do?

### ISSUE THREAD

**Issue by crisfan** [istresearch/scrapy-cluster#156]
hi, madisonb!
scrapy-cluster use a redis server to collect stats and info about spiders, it works normally in ideal conditions.
But sometimes redis server failed with some error, these datas that we collected will be lost and spiders will not work normally.
Is there any good idea to deal with this situation? when redis server failed, spiders can choose a backup redis ser to work.
for example, zookeeper + redis ?

**Comment by damienkilgannon** [comment]
@crisfan could you provide more details on the failure? what is happening? why is Redis failing? Redis is a dependency of scrapy-cluster, scrapy-cluster cannot work without it. I would be more inclined to fix the problems you are having with Redis instead of adding in an alternative fallback option.

**Comment by crisfan** [comment]
@damienkilgannon my redis has not broken down yet, because I generally crawl some small sites, the program finish the task in just a few minutes. there are two real situations that will cause redis failed:
1. if the machine A suddenly loses power， the spiders in machine B and machine C will not aquire requests from redis queue(redis runs on machine A).
2. when the requests in redis queue more and more, server memory can't hold more requests, maybe it will have an out-of-memory problem. so my spiders will not work normally and the requests in redis queue will be lost.
when the redis in machine A broken down, the spiders can aquire requests from the spare redis in machine B, That's what I want to see!

Looking forward to your reply, thanks~~

**Comment by damienkilgannon** [comment]
@crisfan my thoughts would be as follows: keep the request queue in Redis as close to zero as possible. Do this by scaling up your crawler instances that way you will avoid having a lot of requests stuck in your Redis queue and if a hard failure occurs you only lose minimum data. This approach would address both 1 & 2 and on a failure, you can just restart your Redis instance.

**Comment by madisonb** [comment]
Another option is to port/update the logic within Scrapy Cluster to be able to use Redis Cluster instead of a single redis instance. 

This project makes use of https://github.com/andymccurdy/redis-py to conduct redis operations. Redis Cluster is not supported by that library, but instead is at https://github.com/Grokzen/redis-py-cluster (or some other library that is compatible). I am not aware of the write/read inconsistencies we may come across when using Redis Cluster (spec can be found [here](https://redis.io/topics/cluster-spec)), however my main concern would be the pop() mechanism within [this](https://github.com/istresearch/scrapy-cluster/blob/master/utils/scutils/redis_throttled_queue.py) file which controls the cluster crawling speed.

A Pull Request, or improvement to show that switching libraries has 0 impact on the throttled queue performance would be my ideal solution for failsafe redis.

**Comment by crisfan** [comment]
@damienkilgannon  ok, I will try it!

**Comment by crisfan** [comment]
@madisonb that sounds a good idea about use Redis Cluster, I will try it in the comming days!
Receiving your reply is very helpful to a student!

**Comment by alwaysR9** [comment]
I also have thoughts about this problem. Here is my thoughts:
1. Limit the number of urls in redis before the memory of redis overflow. this may be can be done in kafka_monitor module.
2. Use a larger k-v database, for example leveldb. But this method is not completely safe, overflow would happen in extreme case.

Any suggestion would be appreciated.
