### ISSUE TITLE
Support for Tor + Privoxy

### ISSUE THREAD

**Issue by Paw2Pom** [istresearch/scrapy-cluster#157]
Since scrapy-cluster is doing large distributed crawling, any plan to integrate it into Tor + Privoxy for auto-IP rotating crawling?

Cheers

**Comment by madisonb** [comment]
If you wish to actually crawl .onion links that is a specific implementation of this project and not going to be implemented (since you can find Scrapy tutorials online to help you configure it).

If you wish to use Tor to hide/anonymize your IP address, it goes against this project's philosophy for the following reasons.
* You are doing massively distributed crawling on an already slow/overloaded Tor network. Crawling through Tor just to hide your ip address can potentially overload nodes within the network, preventing normal citizens who are trying to circumvent internet restrictions access to websites you take for granted
* Crawling on Tor means that the websites you hit are exposed to Tor exit node IP addresses, and if you crawl fast enough, you will get the endpoint banned from that website. Now, anytime a normal user on Tor tries to hit that website, they are denied because their IP and your crawler IP are identical, because you came from the same exit nodes
* There is no control over your final public IP - even if points 1 and 2 were okay, Tor doesnt guarantee between sessions that your connection always comes from the same exit node, you are much better off using a VPN.

If you would like further reading, please see [this](https://tor.stackexchange.com/a/68) Stack Overflow question (both bit torrent and large scale crawling have a similar net effect), followed up by [this](https://blog.torproject.org/bittorrent-over-tor-isnt-good-idea).

My point is, that this project will not condone scraping on the tor network simply to anonymize your ip address, my recommendation if you need such a service would be to use a paid/hosted VPN and route your crawls through that. If your intention was to just scrape .onion websites, you can fork this project and configure everything on your own, as my goal is to make this project as minimal as possible so it does not become overly complex supporting lots of different use cases.

Closing.
