### ISSUE TITLE
DUPEFILTER_CLASS Doesn't Work

### ISSUE THREAD

**Issue by jamesliu668** [istresearch/scrapy-cluster#177]
Hello,

From the scrapy project, I find that I can change the setting DUPEFILTER_CLASS to overwrite the class, however, this setting doesn't work in scrapy-cluster any more.

Here is the setting in scrapy: [DUPEFILTER_CLASS](https://doc.scrapy.org/en/latest/topics/settings.html?highlight=DUPEFILTER_CLASS)

**Comment by madisonb** [comment]
Scrapy Cluster uses a customized scheduler, and therefore needs a customized deduplication filter due to its distributed nature. You are free to modify the [RFPDupeFilter](https://github.com/istresearch/scrapy-cluster/blob/master/crawler/crawling/redis_dupefilter.py) implementation to meet your needs, but keep in mind it may not give you the behavior you expect.
