### ISSUE TITLE
Integrate Travis CI for offline tests

### ISSUE THREAD

**Issue by jasonrhaas** [istresearch/scrapy-cluster#19]
Since the offline tests don't have external dependencies (kafka, redis, etc), we could automatically run them upon any new commits or pull requests to the repo.  Travis CI is easy to set up and is free for open source repos.  I can also add a badge to show that the offline tests have successfully passed or failed.

**Comment by madisonb** [comment]
@jasonrhaas - thanks to @quasiben this can be closed with his pull request, we just need to add the project to our istresearch travis ci org. Can you take care of this since you set up our other json-transporter project? It would be nice to be able to do builds off of both `dev` and `master` while we continue to work on things.

**Comment by jasonrhaas** [comment]
@madisonb I'll get on that and add it to Travis

**Comment by madisonb** [comment]
@jasonrhaas is this closed?

**Comment by jasonrhaas** [comment]
@madisonb yea but it needs to be be merged to `master` branch.
