### ISSUE TITLE
Is this project no longer supported?

### ISSUE THREAD

**Issue by flyingdev** [istresearch/scrapy-cluster#266]
This project looks good and looks some packages are outdated.

Is this project no longer supported?

Thank you

**Comment by madisonb** [comment]
The original work for this project was created under a contract that required the team to open source it. That contract has since expired, and the team continues to maintain a fork of the open source project internally. 

This internal project is still very active but only maintenance or bug fixes are applied to the open source version as the new maintainers see fit. I think PR's and issues are still looked at, but unfortunately given fairly low priority given how the development is currently funded. 

Thanks for your interest! If this answers your question please close this issue.

**Comment by flyingdev** [comment]
That makes sense.
