### ISSUE TITLE
Pass "spiderid" param to feed function and got "invalid json received" error

### ISSUE THREAD

**Issue by rocdeng** [istresearch/scrapy-cluster#35]
From http://scrapy-cluster.readthedocs.org/en/latest/topics/kafkamonitor.html?highlight=feed#scraper-schema-json I found I could pass "spiderid" to feed function. So I did like this: python kafka-monitor.py feed -s settings_crawling.py '{"url": "http://istresearch3.com", "appid":"testapp", "crawlid":"ABC123", "spiderid":"aaaa"}'. And then I got the "invalid json received" error, I've check the kafka-monitor.py source code and didn't know why.
My purpose of this is that I want to put different links into one single db, and let different spiders (ex: spidera get job from "aaaa:queue" and spiderb  get job from "bbbb:queue") get their own job queue. Am I doing it in the right way?

**Comment by madisonb** [comment]
Your approach is correct, if you would like to add your own spider you can alter the `scraper_schema.json` file and add another enum at the `spiderid` key declaration:

```
"spiderid": { 
    "type": "string",
    "enum": ["link", "aaaa"],
    "default": "link"
},
```
New API requests for your new spider will add a redis key `aaaa:queue` in your redis instance where crawl requests for your new spider named `aaaa` will live. 

This issue is not present in Scrapy Cluster 1.1 - which is in development on the `dev` branch. If you would like more help please consider working from the `dev` branch of this project (1.1 vs 1.0) as there are many improvements to help you debug your program.

**Comment by rocdeng** [comment]
Oh, I did read the scraper_schema.json file and see the section, but I didn't know I should add spiderid into the enum section. Thanks a lot and maybe this could be added into the user guide :)
