### ISSUE TITLE
Python 3 Support

### ISSUE THREAD

**Issue by madisonb** [istresearch/scrapy-cluster#46]
With Scrapy soon supporting Python 3, we should consider supporting it as well. At a first glance, most of the functionality changes do not affect the code within, but I am sure there needs to be more work done.

**Comment by madisonb** [comment]
As of 5-11-16 the 1.1.0 release of Scrapy supports python 3. The code in here should be python 3 compatible before upgrading and closing this ticket

**Comment by madisonb** [comment]
Work on this has been started on the [futurize](https://github.com/istresearch/scrapy-cluster/tree/futurize) branch. As of right now there is an outstanding `scutils` pickling issue in python 3 for the Redis Queue class, which cascades and causes a lot of the integration tests to fail. BUT for now at least I have got the offline tests working.

**Comment by PradeepJaiswar** [comment]
Any update on support for python 3 ?

**Comment by madisonb** [comment]
There is still an outstanding issue that prevents this from pushing forward. I am open to suggestions on how to preserve functionality while supporting Python 3, but lately I have not had a chance to look at this again.

**Comment by madisonb** [comment]
The most recent issue I face right now is that in the `RedisPriorityQueue` class (of which the scrapers use to prioritize their crawling) doesnt seem to play nice with the new python3 pickle `dumps()` return value.

`pickle.dumps()` in python 3 returns bytes which is fine, but we use the return value as the key of a dictionary which we then pass to redis when inserting into the sorted set. This becomes a dictionary that looks like `{ret_val: priority}`. In python 2, `ret_val` is a string and priority is the number. In python 3, `ret_val` is bytes and priority is a number. This plays nicely with python dictionaries just fine, you would never know the difference.

The problem then is that in redis-py, `zadd()` expects a `str` arguments in *both* python 2 and python 3. So when you unpack the dictionary, it passes `redis_key, key1 (bytes), val1` and therefore fails. 

Insight into this would be appreciated, as I am still trying to figure out python 3.

**Comment by madisonb** [comment]
Conversation @joequery and I had internally,
```
return pickle.dumps(item, protocol=2).decode('latin1')
```
may work when using the pickle protocol in both python2 and python3 land without having to write a migration job. The protocol currently is set to `-1` which in python2 defaults to `2` so this is compatible with both python 2/3.

More testing of this is needed but it is a good start. I verified in the python shell that both python versions worked with the internal priority queue code.

**Comment by damienkilgannon** [comment]
When I was testing 
```
return pickle.dumps(item, protocol=2).decode('latin1')
```
in python 2 a unicode object was returned and in python 3 I was getting a string object. Not sure what was up with that. However, I have found another solution which allows us to send either string or bytes to redis. Enabling it to work with both py2 and py3 with out changing how sterilization operates. Instead of using the `zadd()` method we can use the `execute_command()` method. 
e.g.
```
self.server.execute_command('ZADD', self.key, -priority, data)
```

**Comment by madisonb** [comment]
redis-py itself is just executing a `zadd` command as well, although in a much more agnostic way than the above. See https://git.io/v9A4o

The goal I would like to have is to be in a place where upgrading from python 2 to python 3 doesnt require a [migration job](https://github.com/istresearch/scrapy-cluster/blob/master/migrate.py), but the data can lay at rest and be picked up by a python 3 based cluster. In a similar manner, introducing python 3 compatibility with `scutils` shouldn't break existing code that is operating normally on python 2.

**Comment by damienkilgannon** [comment]
Using `execute_command` instead of `zadd` will meet that goal, when `zadd` is used it iters over the kwargs passed to it and this fails when there are byte strings passed. Using `execute_command` just bypasses this and works fine. Note that the scrapy-redis project also took this same approach to get around the problem. https://github.com/rolando/scrapy-redis/commit/7c29f5b651665bbd30cb827564888f93a7f2ed1b 

One other scutils test is failing:

`----------------------------------------------------------------------FAIL: test_purge_old (__main__.TestStatsThreaded)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/online.py", line 131, in test_purge_old
    self.assertEqual(['default_counter:2015-10'], self.redis_conn.keys(tc.get_key() + ':*'))
AssertionError: Lists differ: ['default_counter:2015-10'] != [b'default_counter:2015-10']

First differing element 0:
default_counter:2015-10
b'default_counter:2015-10'

- ['default_counter:2015-10']
+ [b'default_counter:2015-10']
?  +


----------------------------------------------------------------------ok`

Need to explicitly decode the byte string returned from redis to match the regular string which was added.

**Comment by madisonb** [comment]
Python 3 support is now unblocked thanks to the PR above.

**Comment by madisonb** [comment]
Closing. Now supported on the `dev` branch.
