### ISSUE TITLE
Multiple instances of "kafka_monitor" and "redis_monitor"

### ISSUE THREAD

**Issue by SHSE** [istresearch/scrapy-cluster#60]
It is possible to run multiple instances of `kafka_monitor` and `redis_monitor` in a single cluster?

The idea is to setup high availability for these services.

**Comment by madisonb** [comment]
Scrapy Cluster 1.1 does not support this, but 1.2 will. The `dev` branch has the latest 1.2 code with the following:

The Kafka Monitor has been upgraded to scale horizontally, and as long as you have the `KAFKA_GROUP` the same they will consume in unison from the incoming topic. Note that it is important you have the exact same plugin settings on all consumers, or you risk matching messages on one and not the other. 

The Redis Monitor needs a bit of work to support scaling horizontally, which involves a locking functionality on jobs via RedLock and to spawn and manage job processes (as they may take a long time). That work is outlined on #43. In order to be RedLock thread safe (which is what we want) AND have the jobs be non-blocking, we will need a bit of overhead to kick requests off.

**Comment by madisonb** [comment]
Does this answer your question? Otherwise there are other issues that track your request and I am going to close this.

**Comment by SHSE** [comment]
@madisonb, yes, thank you for the answer.
