### ISSUE TITLE
Concurrent requests from a spider to a domain

### ISSUE THREAD

**Issue by l-easwar-akiyama** [istresearch/scrapy-cluster#61]
Hi madisonb,

Currently i am working in a single spider cluster ( 1 machine ).

Scrapy supports concurrent requests to a domain from a single spider. I had tried to emulate this in scrapy-cluster but no luck. Even if i increase queue hits, it just increases the total number of requests it can take from redis within the window. But the requests are still processed one at a time, which ultimately becomes a bottleneck.

Only way i could find to parallelise requests is to spawn two identical spiders with different names and dividing seed urls between them. 

I maybe wrong, but please tell me if there is any way to parralelise requests within a machine.

**Comment by madisonb** [comment]
If you spawn multiple spiders within the same machine, you can easily parallelize to the number of concurrent requests you would like to make. Scrapy's `CONCURRENT_REQUESTS` applies to the downloader middleware and as far as I know should still be operating as it is designed.

In practice we typically run 10-20 spiders of a given type on one machine, and then have many different machines with many different IP addresses so you can really scale out wide without having an individual IP address with a heavy footprint.

You may also want to check out the advanced documentation [here](http://scrapy-cluster.readthedocs.io/en/latest/topics/advanced/productionsetup.html#crawler-configuration) for recommended production crawling setups. Keep in mind some sites will monitor and block spiders who hit them too fast (which is what you are doing when you increase the `QUEUE_HITS` setting), so upping your crawl rate from the same machine may bring you closer to being blocked.

**Comment by l-easwar-akiyama** [comment]
Thanks for the fast reply!

Some more points / questions that i would like to add :

1) For some reason adding / changing `CONCURRENT_REQUESTS` seems to have no affect. The spider still processes sequentially.

2) Increasing `QUEUE_HITS` indeed increases rate of crawling, but it does not concurrently process requests. It's just like a max cap on the hits per window, which anyway bottlenecks to the ISP speed as each request is sequentially processed.

3) _**In practice we typically run 10-20 spiders of a given type on one machine.**_  Does this mean you are running the same spider 20 times or different spiders of the same type ? I am more interested in how to achieve the first case because i only have one spider per type.

4) Currently the only way in which i could parallelise requests was to spawn multiple process of same spider by running `scrapy runspider crawling/spiders/abc.py` multiple times

5) I tried to do this from a single script that was mentioned here : [Multiple Spiders in Single Process](https://github.com/istresearch/scrapy-cluster/issues/18). This is my script 

```
import scrapy
from twisted.internet import reactor
from scrapy.crawler import CrawlerRunner
from crawling.spiders.abc import AbcSpider
from scrapy.utils.project import get_project_settings

runner = CrawlerRunner(get_project_settings())
for i in range(10):
	runner.crawl(AbcSpider)
d = runner.join()
d.addBoth(lambda _: reactor.stop())
reactor.run()
```

But this doesn't work in the expected way. Any suggestions in a proper way to parallelize a single spider ?

**Comment by madisonb** [comment]
1) If you are looking at logs then it will appear like everything is happening sequentially, but how Scrapy uses the downloader middleware is beyond our control. The scheduler releases requests to the twisted backend, which then goes and does the fetching or the url.

2) `QUEUE_HITS` is not based only upon the single spider process you are running, it is a higher level setting that allows coordinated crawling based on the spider's machine and/or ip address. You can read more about that [here](http://scrapy-cluster.readthedocs.io/en/latest/topics/crawler/controlling.html). 

3) Yes. You can run `scrapy runspider crawling/spiders/abc.py &` over and over until you get the desired number of spiders. I recommend you use a process manager like Supervisord though.

4) Right. This project allows you to do that because it orchestrates crawls between processes on the same or different machines.

5) While I didn't test your code snippet, you can look at the logs to see if spiders are being spawned and/or torn down. You still need to use the Kafka Monitor to submit and process requests, as the spiders themselves are just one piece of the puzzle.

Honestly to parallelize the spider it is super easy to install Supervisord and let it spawn multiple processes of your spider, we have been very happy with that approach.

**Comment by l-easwar-akiyama** [comment]
Thanks madisonb!

I am sure that spiders are spawned correctly, but still that wasn't the right way to run. I'll checkout Supervisord.

**Comment by sandykathuria3** [comment]
Assume i am running a spider on IP = A
Then where to define the IP address of the spider running on 'A' , such that crawling should be according to spider running on IP address 'A' only .

??

**Comment by shenbakeshkishore** [comment]
How to use multiple virtual IPs in scrapy-cluster?

**Comment by shenbakeshkishore** [comment]
Also help me with the retry mechanism of failed requests in splinter. My plan is to deal with the selenium_exceptions during browsing using the splinter, and put them to the redis queue with minimum priority, looking for your opinion. If share a sample code. Thanks is advance.

**Comment by madisonb** [comment]
@shenbakeshkishore Multiple virtual IPs would be a scrapy thing, not a scrapy cluster thing. This project modifies the scheduler pretty heavily but you should be able to use middlewares and whatnot. I think you should handle exceptions just like scrapy does, which is to retry them for a couple times and then fail.
