### ISSUE TITLE
Cloned it. Did vagrant up, but couldn't get past step 3. 

### ISSUE THREAD

**Issue by DavidHazeldenUK** [istresearch/scrapy-cluster#81]
Could add a note on the Readme, that it won't work on Windows Vagrant/Virtualbox.

ERROR:-

Running provisioner: ansible...
Windows is not officially supported for the Ansible Control Machine.
Please check https://docs.ansible.com/intro_installation.html#control-machine-requirements

Scrapy Cluster test environment

To set up a pre-canned Scrapy Cluster test environment, make sure you have the latest Virtualbox + Vagrant >= 1.7.4 installed. Vagrant will automatically mount the base scrapy-cluster directory to the /vagrant directory, so any code changes you make will be visible inside the VM.
Steps to launch the test environment:

    vagrant up in base scrapy-cluster directory.
    vagrant ssh to ssh into the VM.
    sudo supervisorctl status to check that everything is running.
    virtualenv sc to create a virtual environment
    source sc/bin/activate to activate the virtual environment
    cd /vagrant to get to the scrapy-cluster directory.
    pip install -r requirements.txt to install Scrapy Cluster dependencies.
    ./run_offline_tests.sh to run offline tests.
    ./run_online_tests.sh to run online tests (relies on kafka, zookeeper, redis).

**Comment by madisonb** [comment]
Interesting, I have not ran into this issue but am happy to add a note. You have a number of options available to you:
- Use the docker containers for the `dev` branch located on dockerhub, and use compose
- If ansible itself is supported on Windows, you can start your own Virtual machine and just change the provisioning script to point to your new virtual machine. Centos and Ubuntu are both supported
- If ansible is not supported on windows, but you can install it on a virtual machine, you can do your work from within the VM and provision to `localhost` instead of a remote machine via ansible
- If you have access to AWS or some other cloud solution, you can always conduct your work there as well.

How about I append a note to both `master` and `dev` readme that says:
`To set up a pre-canned Scrapy Cluster test environment, make sure you have the latest Virtualbox + Vagrant >= 1.7.4 installed. Vagrant will automatically mount the base scrapy-cluster directory to the /vagrant directory, so any code changes you make will be visible inside the VM. Please note that at time of writing this will not work on a Windows machine.
`
