### ISSUE TITLE
callback Issues

### ISSUE THREAD

**Issue by rksaxena** [istresearch/scrapy-cluster#88]
Firstly, thanks for a wonderful project. It is really helpful in scaling web crawling without much efforts.
The issue I am facing is that I am trying to add a callback function other than the `parse` method in `Request` object but on doing so, callback function is not getting called while parse() gets called everytime.
Snippet.
```
req = Request(url, callback=self.parse_contents)
for key in response.meta.keys():
    req.meta[key] = response.meta[key]
yield req
```
If I move the `parse_contents` code within parse function, everything works fine but to do so I have to a couple of checks that I wish to avoid. So, is the callback function supposed to be only `parse` function or am I missing something.

**Comment by madisonb** [comment]
@rksaxena I don't think you are astray, I would presume the functionality is not working since it is not exercised very often (if at all). The support for callbacks was a request from another user and added in [this](https://github.com/istresearch/scrapy-cluster/commit/ec2a817ec8ebc95d32eb65a699b16977e1a47f2b) commit, but it appears like that was the extent of it.

You can see in this method [here](https://github.com/istresearch/scrapy-cluster/blob/master/crawler/crawling/distributed_scheduler.py#L445) that the callback in the item retrieved is never actually checked, and the request yielded to the scheduler appears like it will never include that callback/errback that was passed through.

I would have to do some testing to see if we can just use the function name, or we actually have to find and grab the spider's actual method here - either way I think it should be possible to get working correctly.

Pseudocode like so in the `next_request()` method linked above:
```python
if 'callback' in item:
    req.callback = item['callback'] # if string is allowed, otherwise
    req.callback = self.find_real_spider_callback_method(item['callback']) # where that method would return the self.spider.function_instance based on the string parameter

# same thing for 'errback'
```

How does that sound?

**Comment by rksaxena** [comment]
This sounds good! I think `req.callback = item['callback']` should work.
I had checked `request_to_dict` method where the request object parameters were being copied so I assumed that it would also be getting used as well.

**Comment by madisonb** [comment]
@rksaxena Please check the `dev` branch and associated docker containers for the update I just made. I created an simple spider that generated different requests with different callback methods and everything seems to work correctly. 

If this solves your problem please close this!

**Comment by rksaxena** [comment]
Thanks @madisonb !!
I used the patch in my existing code and it is working perfectly.

**Comment by nguyenanhnhat** [comment]
HI rksaxena How you do it . teach me please. I have a problem with callback a my parse function

**Comment by rksaxena** [comment]
@nguyenanhnhat : Patch the code from this [commit](https://github.com/istresearch/scrapy-cluster/commit/8cb4f3dd570c647997bbcea1b8bbe76c9408eee7) in the ```crawler/crawling/distributed_scheduler.py``` and it should work
