### ISSUE TITLE
moderate throttling not works as expected

### ISSUE THREAD

**Issue by softwarevamp** [istresearch/scrapy-cluster#89]
i have below throttle settings:
```
QUEUE_HITS = 33
QUEUE_WINDOW = 60
```
But i can send out 285 requests only in 10 minutes, that is significantly smaller than my expected rates.

**Comment by softwarevamp** [comment]
seems the moderation not works perfectly

**Comment by softwarevamp** [comment]
@jasonrhaas can you please check it, thanks a lot!

**Comment by madisonb** [comment]
@softwarevamp do you have the `QUEUE_MODERATED` flag set to `True`? It comes that way by default in order to spread the server hits across the time period, however I think your issue is a direct manifestation of #47, where when the throttle is ran under scrapy operation it causes a drift and doesn't actually hit it's expected value.

You can see for yourself with [this](http://scrapy-cluster.readthedocs.io/en/latest/topics/utils/redisthrottledqueue.html) page's example usage down near the bottom, where the throttle behaves as expected. But when under operation within the scheduler, there is a drift.

In your example, you should expect 330 hits in 10 mins, instead of 285. As a workaround for now, you could set the queue hits higher (to say, 45) and you would get closer to your expected results.

**Comment by softwarevamp** [comment]
#47 addresses my issue exactly, sorry i didn't reach that page.
